### ISSUE TITLE
Django 1-5-5 startup error

### ISSUE THREAD

**Issue by kitsuneymg** [dndtools/dndtools#66]
When trying to run, I get this:
# ~/dndtools/dndtools>python manage.py runserver 0.0.0.0:8000

Validating models...

Unhandled exception in thread started by <bound method Command.inner_run of <django.contrib.staticfiles.management.commands.runserver.Command object at 0x191a350>>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 93, in inner_run
    self.validate(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 280, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/validation.py", line 35, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 166, in get_app_errors
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 72, in _populate
    self.load_app(app_name, True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 96, in load_app
    models = import_module('.models', app_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/models.py", line 32, in <module>
    load_panel_classes()
  File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/toolbar/loader.py", line 96, in load_panel_classes
    (panel_module, e))
django.core.exceptions.ImproperlyConfigured: Error importing debug panel debug_toolbar.panels.versions: "No module named versions"

**Comment by thomasfa18** [comment]
I've authored a fix that I believe resolves this issue...
There is currently a pull request into the main project but if you wish you can retrieve it from my the branch of my current for https://github.com/thomasfa18/dndtools/blob/patch-3/dndtools/dndproject/local.py.sample
recreate your local.py from this, or edit your current local.py to remove or comment out the degug toolbar section:
+    DEBUG_TOOLBAR_PANELS = (
+        'debug_toolbar.panels.versions.VersionsPanel',
+        'debug_toolbar.panels.timer.TimerPanel',
+        'debug_toolbar.panels.settings.SettingsPanel',
+        'debug_toolbar.panels.headers.HeadersPanel',
+        'debug_toolbar.panels.request.RequestPanel',
+        'debug_toolbar.panels.sql.SQLPanel',
+        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
+        'debug_toolbar.panels.templates.TemplatesPanel',
+        'debug_toolbar.panels.cache.CachePanel',
+        'debug_toolbar.panels.signals.SignalsPanel',
+        'debug_toolbar.panels.logging.LoggingPanel',
+        'debug_toolbar.panels.redirects.RedirectsPanel',
+    )

hope this helps

**Comment by Kovasuel** [comment]
Confirmed to restore functionality, though I'm not well enough versed to know if this breaks other aspects of the code. Know just enough to be dangerous here...

**Comment by vkgyl2432** [comment]
is this issue fixed yet?
I am still getting this error message on my server.
